name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Setup database and generate static data
        env:
          DATABASE_URL: file:./api/db/dev.db
        run: |
          # Create the database directory if it doesn't exist
          mkdir -p api/db
          # Start the development server in the background
          yarn rw dev &
          # Wait for the server to start
          sleep 10
          # Run database migrations
          yarn rw prisma migrate deploy
          # Generate static data
          node scripts/generateStaticData.js
          # Stop the development server
          pkill -f "yarn rw dev"

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Build
        run: |
          ./build.sh
          ls -la dist/
          echo "Build completed"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
